const projects = [
  {
    id: "1",
    projectName: 'Rick and Morty - Characters',
    description: 'This project is a single page application developed in ReactJs. It shows a list of different characters depending of the location that the user could search. It has dynamic pagination, a helper input that helps you to find a location and a system to control different errors that the API could return.',
    image1: "/build/Img/Projects/RickAndMorty/1.png",
    image2: "/build/Img/Projects/RickAndMorty/code.png",
    image3: "/build/Img/Projects/RickAndMorty/2.jpeg",
    image4: "/build/Img/Projects/RickAndMorty/3.png",
    image5: "/build/Img/Projects/RickAndMorty/4.jpeg",
    image6: "/build/Img/Projects/RickAndMorty/5.png",
    gitHubUrl: "https://github.com/sauloroman/RickandMortyAppReact",
    liveUrl: "https://rickandmortyappsrsn.netlify.app/"
  },
  {
    id: "2",
    projectName: 'Converter of numbering systems',
    description: 'Project developed with HTML, CSS and JavaScript for the conversion of numbers between base 2, base 8, base 16 and base 10 numbering systems. Object oriented programming is used.',
    image1: "/build/Img/Projects/Convertidor/1.png",
    image2: "/build/Img/Projects/Convertidor/code.png",
    image3: "/build/Img/Projects/Convertidor/2.jpg",
    image4: "/build/Img/Projects/Convertidor/3.png",
    image5: "/build/Img/Projects/Convertidor/4.jpeg",
    image6: "/build/Img/Projects/Convertidor/5.png",
    gitHubUrl: "https://github.com/sauloroman/ConverterJS",
    liveUrl: "https://convertidorsistemassrsn.netlify.app/"
  },
  {
    id: "3",
    projectName: 'Landing Page - creatives',
    description: 'Landing Page of a site called Sunnyside, this project is the result of a challenge in FrontEnd Mentor successfully. Made with the three fundamental web technologies, HTML5, CSS3 and JS. It features animations, responsive design and mobile menu.',
    image1: "/build/Img/Projects/Creatives/1.png",
    image2: "/build/Img/Projects/Creatives/code.png",
    image3: "/build/Img/Projects/Creatives/2.jpg",
    image4: "/build/Img/Projects/Creatives/3.png",
    image5: "/build/Img/Projects/Creatives/4.jpeg",
    image6: "/build/Img/Projects/Creatives/5.png",
    gitHubUrl: "https://github.com/sauloroman/SunnysiteSRSN",
    liveUrl: "https://sunnysitesrsn.netlify.app/"
  },
  {
    id: "4",
    projectName: 'Weather App',
    description: 'Weather App is a project developed with React and consumption of the OpenWeatherApp API, you can check some real-time weather features in many cities around the world.',
    image1: "/build/Img/Projects/Clima/1.png",
    image2: "/build/Img/Projects/Clima/code.png",
    image3: "/build/Img/Projects/Clima/2.jpg",
    image4: "/build/Img/Projects/Clima/3.png",
    image5: "/build/Img/Projects/Clima/4.jpeg",
    image6: "/build/Img/Projects/Clima/5.png",
    gitHubUrl: "https://github.com/sauloroman/WeatherAppReact2",
    liveUrl: "https://appweathersrsn.netlify.app/"
  },
  {
    id: "5",
    projectName: 'Landing Page - Nucleus',
    description: 'Landing page of a credit card called Nucleus where various techniques of applying CSS styles are displayed. The BEM methodology was applied.',
    image1: "/build/Img/Projects/Nucleus/1.png",
    image2: "/build/Img/Projects/Nucleus/code.png",
    image3: "/build/Img/Projects/Nucleus/2.jpg",
    image4: "/build/Img/Projects/Nucleus/3.png",
    image5: "/build/Img/Projects/Nucleus/4.jpeg",
    image6: "/build/Img/Projects/Nucleus/5.png",
    gitHubUrl: "https://github.com/sauloroman/NucleusCSS",
    liveUrl: "https://nucleussrsn.netlify.app/"
  },
  {
    id: "6",
    projectName: 'Landing Page - TechPRO',
    description: 'Project elaborated with HTML and CSS on some audifonos denominated TechPRO. Project totally responsive and with the methodology of writing code BEM',
    image1: "/build/Img/Projects/Audifonos/1.png",
    image2: "/build/Img/Projects/Audifonos/code.png",
    image3: "/build/Img/Projects/Audifonos/2.jpg",
    image4: "/build/Img/Projects/Audifonos/3.png",
    image5: "/build/Img/Projects/Audifonos/4.jpeg",
    image6: "/build/Img/Projects/Audifonos/5.png",
    gitHubUrl: "https://github.com/sauloroman/TechPROCSS",
    liveUrl: "https://techprosrsn.netlify.app/"
  },
  {
    id: "7",
    projectName: 'Landing Page - Bookmark',
    description: 'BookMark is a FrontEnd Mentor challenge that reflects the use of HTML, CSS and JS, employs responsibility and features numerous animations. The implementation of a slice with JavaScript is a feature to highlight.',
    image1: "/build/Img/Projects/BookMark/1.jpg",
    image2: "/build/Img/Projects/BookMark/code.png",
    image3: "/build/Img/Projects/BookMark/2.jpeg",
    image4: "/build/Img/Projects/BookMark/3.png",
    image5: "/build/Img/Projects/BookMark/4.jpeg",
    image6: "/build/Img/Projects/BookMark/5.png",
    gitHubUrl: "https://github.com/sauloroman/BookMark-Landing-Page",
    liveUrl: "https://bookmarksrsn.netlify.app/"
  },
  {
    id: "8",
    projectName: 'Expense Planner',
    description: 'Application developed in React JS to manage the expenses that a person can have, with filtering, dynamic calculation, creation, editing and elimination of expenses.',
    image1: "/build/Img/Projects/Planificador/1.png",
    image2: "/build/Img/Projects/Planificador/code.png",
    image3: "/build/Img/Projects/Planificador/2.jpg",
    image4: "/build/Img/Projects/Planificador/3.png",
    image5: "/build/Img/Projects/Planificador/4.jpeg",
    image6: "/build/Img/Projects/Planificador/5.png",
    gitHubUrl: "https://github.com/sauloroman/AdministradorGastosReact",
    liveUrl: "https://administradorsrsn.netlify.app/"
  },
  {
    id: "9",
    projectName: 'Landing Page - Omnifood',
    description: 'Landing Page of a startup dedicated to sending food packages. Project made in HTML, CSS and JS, 100% responsive.',
    image1: "/build/Img/Projects/Omnifood/1.png",
    image2: "/build/Img/Projects/Omnifood/code.png",
    image3: "/build/Img/Projects/Omnifood/2.jpg",
    image4: "/build/Img/Projects/Omnifood/3.png",
    image5: "/build/Img/Projects/Omnifood/4.jpeg",
    image6: "/build/Img/Projects/Omnifood/5.png",
    gitHubUrl: "https://github.com/sauloroman/OmnifoodSRSN",
    liveUrl: "https://omnifood-srsn.netlify.app/"
  },
  {
    id: "10",
    projectName: 'ToDo List',
    description: 'Application for the management and organization of tasks. JavaScript and Local Storage are present in this project. It has an alert system and dynamic interaction.',
    image1: "/build/Img/Projects/ToDo/1.png",
    image2: "/build/Img/Projects/ToDo/code.png",
    image3: "/build/Img/Projects/ToDo/2.jpeg",
    image4: "/build/Img/Projects/ToDo/3.png",
    image5: "/build/Img/Projects/ToDo/4.jpeg",
    image6: "/build/Img/Projects/ToDo/5.png",
    gitHubUrl: "https://github.com/sauloroman/ToDo-List-HTML-CSS-JS/tree/main",
    liveUrl: "https://mistareas-srsn.netlify.app/"
  },
  {
    id: "11",
    projectName: 'CRUD React App',
    description: `As proof of the use of HTTP methods, I developed this responsive web application that allows you to perform the four operations of digital data management: create, read, update and delete. To achieve this, everything was based on an API that handles user administration. The application has modal windows and a user-friendly graphical interface. Form handling is delegated to a library known as "React Hook Form" that helps prevent errors.`,
    image1: "/build/Img/Projects/CRUD/1.png",
    image2: "/build/Img/Projects/CRUD/code.png",
    image3: "/build/Img/Projects/CRUD/2.jpeg",
    image4: "/build/Img/Projects/CRUD/3.png",
    image5: "/build/Img/Projects/CRUD/4.jpeg",
    image6: "/build/Img/Projects/CRUD/5.png",
    gitHubUrl: "https://github.com/sauloroman/USERSCRUDREACT",
    liveUrl: "https://userscrudroman.netlify.app/"
  },
  {
    id: "12",
    projectName: 'Shopping Cart',
    description: 'Project elaborated in HTML, CSS and JavaScript, making use of modules, array methods, local storage. Shopping cart simulator that makes calculations and emulates payment on a platform',
    image1: "/build/Img/Projects/Cart-project/1.png",
    image2: "/build/Img/Projects/Cart-project/code.png",
    image3: "/build/Img/Projects/Cart-project/2.jpeg",
    image4: "/build/Img/Projects/Cart-project/3.png",
    image5: "/build/Img/Projects/Cart-project/4.jpeg",
    image6: "/build/Img/Projects/Cart-project/5.png",
    gitHubUrl: "https://github.com/sauloroman/Shopping-cart---Academlo",
    liveUrl: "https://shoppingcartacademlosauloroman.netlify.app/index.html"
  },
  {
    id: "13",
    projectName: 'Cryptocurrency App',
    description: 'Consumption of an API to display the price of the most popular bitcoins in different currencies. React Styled Components is used, Fetch API, and different React Hooks',
    image1: "/build/Img/Projects/Criptomonedas/1.png",
    image2: "/build/Img/Projects/Criptomonedas/code.png",
    image3: "/build/Img/Projects/Criptomonedas/2.jpeg",
    image4: "/build/Img/Projects/Criptomonedas/3.png",
    image5: "/build/Img/Projects/Criptomonedas/4.jpeg",
    image6: "/build/Img/Projects/Criptomonedas/5.png",
    gitHubUrl: "https://github.com/sauloroman/CriptoMonedasReact",
    liveUrl: "https://cryptomonedassrsn.netlify.app/"
  },
  {
    id: "14",
    projectName: 'Pokedex App',
    description: 'Pokedex is an application in React, React Router and Redux. It has paging, filtering, route protection and individual search. As well as enabling dark mode and custom settings.',
    image1: "/build/Img/Projects/Pokedex/1.png",
    image2: "/build/Img/Projects/Pokedex/code.png",
    image3: "/build/Img/Projects/Pokedex/2.jpeg",
    image4: "/build/Img/Projects/Pokedex/3.png",
    image5: "/build/Img/Projects/Pokedex/4.jpeg",
    image6: "/build/Img/Projects/Pokedex/5.png",
    gitHubUrl: "https://github.com/sauloroman/PokemonAppReact",
    liveUrl: "https://pokemonsrsn.netlify.app/"
  },
  {
    id: "15",
    projectName: 'Guess my number',
    description: 'This application puts into practice my skills with the three web technologies, HTML, Css and JavaScript. It is a game that detects if you have guessed the number that was generated randomly.',
    image1: "/build/Img/Projects/Guess/1.png",
    image2: "/build/Img/Projects/Guess/code.png",
    image3: "/build/Img/Projects/Guess/2.jpeg",
    image4: "/build/Img/Projects/Guess/3.png",
    image5: "/build/Img/Projects/Guess/4.jpeg",
    image6: "/build/Img/Projects/Guess/5.png",
    gitHubUrl: "https://github.com/sauloroman/Guess-my-random-number",
    liveUrl: "https://adivinaminumero-srsn.netlify.app/"
  },
  {
    id: "16",
    projectName: 'Car Search',
    description: 'Use of array methods in JavaScript to achieve automotive filtering depending on user searches. Makes extensive use of callback functions',
    image1: "/build/Img/Projects/Busqueda/1.png",
    image2: "/build/Img/Projects/Busqueda/code.png",
    image3: "/build/Img/Projects/Busqueda/2.jpeg",
    image4: "/build/Img/Projects/Busqueda/3.png",
    image5: "/build/Img/Projects/Busqueda/4.jpeg",
    image6: "/build/Img/Projects/Busqueda/5.png",
    gitHubUrl: "https://github.com/sauloroman/Search-your-car",
    liveUrl: "https://busquedacampossrsn.netlify.app/"
  },
]