const projects = [
  {
    id: "1",
    projectName: 'Rick and Morty - Personajes',
    description: ' Proyecto hecho en React con el consumo de la API Rick and Morty</a>. Busqueda por palabras clave y paginación dinámica. Muestra los personajes que aparecen en determinada locación de la serie, su estado actual ( vivo / muerto ), su origen y la cantidad de apariciones que tienen. Se hizo uso de Axios para el consumo de la API.',
    image1: "/build/Img/Projects/RickAndMorty/1.png",
    image2: "/build/Img/Projects/RickAndMorty/code.png",
    image3: "/build/Img/Projects/RickAndMorty/2.jpg",
    image4: "/build/Img/Projects/RickAndMorty/3.png",
    image5: "/build/Img/Projects/RickAndMorty/4.jpeg",
    image6: "/build/Img/Projects/RickAndMorty/5.png",
    gitHubUrl: "https://github.com/sauloroman/RickAndMortyApp",
    liveUrl: "https://rickandmortysrsn.netlify.com/"
  },
  {
    id: "2",
    projectName: 'Convertidor de sistemas numéricos',
    description: 'Proyecto elaborado con HTML, CSS Y JavaScript destinado a la conversión de números entre sistemás de numeración base 2, base 8, base 16 y base 10. Se hace uso de la programación orientada a objetos.',
    image1: "/build/Img/Projects/Convertidor/1.png",
    image2: "/build/Img/Projects/Convertidor/code.png",
    image3: "/build/Img/Projects/Convertidor/2.jpg",
    image4: "/build/Img/Projects/Convertidor/3.png",
    image5: "/build/Img/Projects/Convertidor/4.jpeg",
    image6: "/build/Img/Projects/Convertidor/5.png",
    gitHubUrl: "https://github.com/sauloroman/ConverterJS",
    liveUrl: "https://convertidorsistemassrsn.netlify.app/"
  },
  {
    id: "3",
    projectName: 'Landing Page - creatives',
    description: 'Landing Page de un sitio denominado Sunnyside, este proyecto es el resultado de un reto en FrontEnd Mentor realizado exitosamente.',
    image1: "/build/Img/Projects/Creatives/1.png",
    image2: "/build/Img/Projects/Creatives/code.png",
    image3: "/build/Img/Projects/Creatives/2.jpg",
    image4: "/build/Img/Projects/Creatives/3.png",
    image5: "/build/Img/Projects/Creatives/4.jpeg",
    image6: "/build/Img/Projects/Creatives/5.png",
    gitHubUrl: "https://github.com/sauloroman/SunnysiteSRSN",
    liveUrl: "https://sunnysitesrsn.netlify.app/"
  },
  {
    id: "4",
    projectName: 'Clima App',
    description: 'Clima App es un proyecto desarrollado con React y el consumo de la API OpenWeatherApp, puedes consultar algunas características climatológicas en tiempo real en muchas ciudades alrededor del mundo.',
    image1: "/build/Img/Projects/Clima/1.png",
    image2: "/build/Img/Projects/Clima/code.png",
    image3: "/build/Img/Projects/Clima/2.jpg",
    image4: "/build/Img/Projects/Clima/3.png",
    image5: "/build/Img/Projects/Clima/4.jpeg",
    image6: "/build/Img/Projects/Clima/5.png",
    gitHubUrl: "https://github.com/sauloroman/WeatherAppReact2",
    liveUrl: "https://appweathersrsn.netlify.app/"
  },
  {
    id: "5",
    projectName: 'Landing Page - Nucleus',
    description: 'Landing Page de una tarjeta de crédito denominada Nucleus donde se muestran diversas técnicas de aplicación de estilos CSS. Se aplicó la metología BEM.',
    image1: "/build/Img/Projects/Nucleus/1.png",
    image2: "/build/Img/Projects/Nucleus/code.png",
    image3: "/build/Img/Projects/Nucleus/2.jpg",
    image4: "/build/Img/Projects/Nucleus/3.png",
    image5: "/build/Img/Projects/Nucleus/4.jpeg",
    image6: "/build/Img/Projects/Nucleus/5.png",
    gitHubUrl: "https://github.com/sauloroman/NucleusCSS",
    liveUrl: "https://nucleussrsn.netlify.app/"
  },
  {
    id: "6",
    projectName: 'Landing Page - TechPRO',
    description: 'Proyecto elaborado con HTML y CSS sobre unos audifonos denominados TechPRO. Proyecto totalmente responsive y con la metodología de escribir código BEM',
    image1: "/build/Img/Projects/Audifonos/1.png",
    image2: "/build/Img/Projects/Audifonos/code.png",
    image3: "/build/Img/Projects/Audifonos/2.jpg",
    image4: "/build/Img/Projects/Audifonos/3.png",
    image5: "/build/Img/Projects/Audifonos/4.jpeg",
    image6: "/build/Img/Projects/Audifonos/5.png",
    gitHubUrl: "https://github.com/sauloroman/TechPROCSS",
    liveUrl: "https://techprosrsn.netlify.app/"
  },
  {
    id: "7",
    projectName: 'Landing Page - Bookmark',
    description: 'BookMark es un reto de FrontEnd Mentor que refleja el uso de HTML, CSS Y JS, emplea la responsabilidad y cuenta con numerosas animaciones.',
    image1: "/build/Img/Projects/BookMark/1.jpg",
    image2: "/build/Img/Projects/BookMark/code.png",
    image3: "/build/Img/Projects/BookMark/2.jpeg",
    image4: "/build/Img/Projects/BookMark/3.png",
    image5: "/build/Img/Projects/BookMark/4.jpeg",
    image6: "/build/Img/Projects/BookMark/5.png",
    gitHubUrl: "https://github.com/sauloroman/BookMark-Landing-Page",
    liveUrl: "https://bookmarksrsn.netlify.app/"
  },
  {
    id: "8",
    projectName: 'Planificador de gastos',
    description: 'Aplicación elaborada en React JS para administrar los gastos que una persona puede tener, con filtrado, calculo dinámico, creación, edición y eliminación de los gastos.',
    image1: "/build/Img/Projects/Planificador/1.png",
    image2: "/build/Img/Projects/Planificador/code.png",
    image3: "/build/Img/Projects/Planificador/2.jpg",
    image4: "/build/Img/Projects/Planificador/3.png",
    image5: "/build/Img/Projects/Planificador/4.jpeg",
    image6: "/build/Img/Projects/Planificador/5.png",
    gitHubUrl: "https://github.com/sauloroman/AdministradorGastosReact",
    liveUrl: "https://administradorsrsn.netlify.app/"
  },
  {
    id: "9",
    projectName: 'Landing Page - Omnifood',
    description: 'Landing Page de una startup dedicada al envío de paquetes de comida. Proyecto elaborado en HTML, CSS Y JS, 100% responsive.',
    image1: "/build/Img/Projects/Omnifood/1.png",
    image2: "/build/Img/Projects/Omnifood/code.png",
    image3: "/build/Img/Projects/Omnifood/2.jpg",
    image4: "/build/Img/Projects/Omnifood/3.png",
    image5: "/build/Img/Projects/Omnifood/4.jpeg",
    image6: "/build/Img/Projects/Omnifood/5.png",
    gitHubUrl: "https://github.com/sauloroman/OmnifoodSRSN",
    liveUrl: "https://omnifood-srsn.netlify.app/"
  },
  {
    id: "10",
    projectName: 'ToDo List',
    description: 'Aplicación destinada a la gestión y organización de tareas. JavaScript y Local Storage están presentes en este proyecto. Cuenta con sistema de alertas e interacción dinámica.',
    image1: "/build/Img/Projects/ToDo/1.png",
    image2: "/build/Img/Projects/ToDo/code.png",
    image3: "/build/Img/Projects/ToDo/2.jpeg",
    image4: "/build/Img/Projects/ToDo/3.png",
    image5: "/build/Img/Projects/ToDo/4.jpeg",
    image6: "/build/Img/Projects/ToDo/5.png",
    gitHubUrl: "https://github.com/sauloroman/ToDo-List-HTML-CSS-JS/tree/main",
    liveUrl: "https://mistareas-srsn.netlify.app/"
  },
  {
    id: "11",
    projectName: 'CRUD React App',
    description: 'En la presente aplicación se hace uso de los métodos HTTP para crear un CRUD de usuarios. Se emplea Axios y React Hook Form.',
    image1: "/build/Img/Projects/CRUD/1.png",
    image2: "/build/Img/Projects/CRUD/code.png",
    image3: "/build/Img/Projects/CRUD/2.jpeg",
    image4: "/build/Img/Projects/CRUD/3.png",
    image5: "/build/Img/Projects/CRUD/4.jpeg",
    image6: "/build/Img/Projects/CRUD/5.png",
    gitHubUrl: "https://github.com/sauloroman/CRUD-REACT",
    liveUrl: "https://crudsrsn.netlify.app/"
  },
  {
    id: "12",
    projectName: 'Shopping Cart',
    description: 'Proyecto elaborado en HTML, CSS Y JavaScript, haciendo uso de módulos, array methods, local storage. Simulador de carrito de compras que hace cálculos y emula el pago en una plataforma.',
    image1: "/build/Img/Projects/Cart-project/1.png",
    image2: "/build/Img/Projects/Cart-project/code.png",
    image3: "/build/Img/Projects/Cart-project/2.jpeg",
    image4: "/build/Img/Projects/Cart-project/3.png",
    image5: "/build/Img/Projects/Cart-project/4.jpeg",
    image6: "/build/Img/Projects/Cart-project/5.png",
    gitHubUrl: "https://github.com/sauloroman/Shopping-cart---Academlo",
    liveUrl: "https://shoppingcartacademlosauloroman.netlify.app/index.html"
  },
  {
    id: "13",
    projectName: 'Criptomonedas App',
    description: 'Consumo de una API para el despliegue del precio de las bitcoins más populares en diferentes divisas. Se hace uso de React Styled Components.',
    image1: "/build/Img/Projects/Criptomonedas/1.png",
    image2: "/build/Img/Projects/Criptomonedas/code.png",
    image3: "/build/Img/Projects/Criptomonedas/2.jpeg",
    image4: "/build/Img/Projects/Criptomonedas/3.png",
    image5: "/build/Img/Projects/Criptomonedas/4.jpeg",
    image6: "/build/Img/Projects/Criptomonedas/5.png",
    gitHubUrl: "https://github.com/sauloroman/CriptoMonedasReact",
    liveUrl: "https://cryptomonedassrsn.netlify.app/"
  },
  {
    id: "14",
    projectName: 'Pokedex App',
    description: 'Pokedex es una aplicación en React, React Router y Redux. Cuenta con paginación, filtrado, protección de rutas y busqueda individual. Así como permite la habilitación de dark mode y configuraciones personalizadas.',
    image1: "/build/Img/Projects/Pokedex/1.png",
    image2: "/build/Img/Projects/Pokedex/code.png",
    image3: "/build/Img/Projects/Pokedex/2.jpeg",
    image4: "/build/Img/Projects/Pokedex/3.png",
    image5: "/build/Img/Projects/Pokedex/4.jpeg",
    image6: "/build/Img/Projects/Pokedex/5.png",
    gitHubUrl: "https://github.com/sauloroman/Pokedex-React",
    liveUrl: "https://pokedexsrsn.netlify.app/"
  },
  {
    id: "15",
    projectName: 'Adivina mi número',
    description: 'Esta aplicación pone en prácticas mis habilidades con las tres tecnlogías web, HTML, Css y JavaScript. Es un juego que detecta si has acertado el número que se generó aleatoriamente.',
    image1: "/build/Img/Projects/Guess/1.png",
    image2: "/build/Img/Projects/Guess/code.png",
    image3: "/build/Img/Projects/Guess/2.jpeg",
    image4: "/build/Img/Projects/Guess/3.png",
    image5: "/build/Img/Projects/Guess/4.jpeg",
    image6: "/build/Img/Projects/Guess/5.png",
    gitHubUrl: "https://github.com/sauloroman/Guess-my-random-number",
    liveUrl: "https://adivinaminumero-srsn.netlify.app/"
  },
  {
    id: "16",
    projectName: 'Busqueda de automóviles',
    description: 'Empleo de los array methods en JavaScript para lograr la filtración de automoviles dependiendo las busquedas del usuario. Hace amplio uso de las funciones callback',
    image1: "/build/Img/Projects/Busqueda/1.png",
    image2: "/build/Img/Projects/Busqueda/code.png",
    image3: "/build/Img/Projects/Busqueda/2.jpeg",
    image4: "/build/Img/Projects/Busqueda/3.png",
    image5: "/build/Img/Projects/Busqueda/4.jpeg",
    image6: "/build/Img/Projects/Busqueda/5.png",
    gitHubUrl: "https://github.com/sauloroman/Search-your-car",
    liveUrl: "https://busquedacampossrsn.netlify.app/"
  },
]